### ISSUE TITLE
Plugin Project-Files DX11.DynamicShader.dll (String-Shader and so on...)

### ISSUE THREAD

**Issue by indigocean** [everoneishappy/FieldTrip#1]
Hello everoneishappy,

your dll is only compiled for 64bit vvvv. please, would you be so good as to add the project-files to self-compile or an single x32 library?

thx for your interresting FieldTrip. Im testing yet...

greets

**Comment by everyoneishappy** [comment]
Hey indigocean I'll take a look.  I think it's targeted to anycpu already, but some of the dependencies might be 64 bit.  tbh I'm a bit of a newbie with Visual Studio still

**Comment by indigocean** [comment]
Hej everyoneishappy, i recompiled your library and i hope i understand your project. i tidy up a little bit and developed a kind of a template... you can just one more copy and paste the original .cs-files to the right place.

[http://www34.zippyshare.com/v/qK2UvwoS/file.html](url)

The structure is: <packs/FieldTrip/src/DX11.DynamicShader/DX11.DynamicShader.sln>

**Comment by everyoneishappy** [comment]
Hey thanks.  I'll take a look at how you did the references.  I think the decompile changed the number of cs files too, so might not copy paste the whole thing.  Happy to share the original source too, it's just not been top priority as still adding modules atm I want to include in first release.

**Comment by everyoneishappy** [comment]
I tried to add a VS project to the pack structure on here, but not working to build atm.  The way all the references work is not really clear to me yet.  The C# files are there now at least.

**Comment by everyoneishappy** [comment]
project files seem to be working in place now.  I don't actually use x32 so please let me know if it works for you.

**Comment by indigocean** [comment]
sorry this was my fault! anycpu with direct references for dx11 and vvvv lib doesnt exists...

here is the current project [http://www115.zippyshare.com/v/AKjG5cG4/file.html](url)

**Comment by everyoneishappy** [comment]
Just setup vvvv_50beta35.8_x86 to test this and seems to work fine with the same dll.
