### ISSUE TITLE
Quality of Help Patches

### ISSUE THREAD

**Issue by wirmachenbunt** [everoneishappy/FieldTrip#4]
is sometimes not optimal. i'm missing comments to understand whats going on...

![quality](https://user-images.githubusercontent.com/1138673/44397735-b7359700-a541-11e8-9ad7-98cfa0113d5e.JPG)

**Comment by everyoneishappy** [comment]
If you check the FieldGuide patches they should be much more nicely documented.  Would probably be nice to add some commentary to these ones too, but probably won't happen anytime too soon :p

For concept of gradient specifically you can check the Gradient (SF2D.Operators) help patch,
or https://en.wikipedia.org/wiki/Gradient.

**Comment by wirmachenbunt** [comment]
ok, thank you. i will have a look.
maybe add this reference to the patch. this is the kind of comment i was talking about ;)
